---
- name: 'Atualiza pacotes e instala nginx'
  apt:
    name: nginx
    update_cache: yes
    state: latest
  notify:
    - start nginx
  become: yes
# Cópia do arquivo para o diretório web do nginx
- name: 'Configura Pagina nginx'
  template:
    src: 'templates/index.html.j2'
    dest: '/usr/share/nginx/html/index.html'
    # verifica se o arquivo foi copiado corretamente
    notify:
      - verifica arquivo
    notify:
      - restart nginx
    # verifica se o serviço do nginx esta iniciado, caso contrário, inicia-o.
    notify:
      - start nginx
    #notify:
    #  - stop nginx
  become: yes