---
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
  become: yes
  
- name: stop nginx
  service:
    name: nginx
    state: stopped
  become: true
# verifica se o arquivo foi copiado corretamente
- name: verifica arquivo
  shell:
    cmd: echo 'arquivo copiado com sucesso'
  become: yes